#ifndef GUARD_CONSTANTS_GYM_LEADER_IDS_H
#define GUARD_CONSTANTS_GYM_LEADER_IDS_H

#define GYM_LEADER_BROCK		0
#define GYM_LEADER_YVONNE		1
#define GYM_LEADER_LEO			2
#define GYM_LEADER_JANINE		3
#define GYM_LEADER_WATTSON		4
#define GYM_LEADER_SABRINA		5
#define GYM_LEADER_VALERIA		6
#define GYM_LEADER_SOREN		7
#define GYM_LEADER_MISTY		8
#define GYM_LEADER_STEEL_PH		9
#define GYM_LEADER_ERICA		10
#define GYM_LEADER_BLAINE		11
#define GYM_LEADER_BLUE			12

#define NUM_GYM_LEADERS			GYM_LEADER_BLUE + 1


#define GYM_LEVEL_1				0
#define GYM_LEVEL_2				1
#define GYM_LEVEL_3				2
#define GYM_LEVEL_4				3


#endif	//GUARD_CONSTANTS_GYM_LEADER_IDS_H
