#ifndef GUARD_WEATHER_CLASS
#define GUARD_WEATHER_CLASS

#define WEATHER_NONE	 		0
#define WEATHER_TEMPERATE		1
#define WEATHER_WARM_1			2
#define WEATHER_WARM_2			3
#define WEATHER_HOT_1			4
#define WEATHER_HOT_2			5
#define WEATHER_NO_SUN			6
#define WEATHER_COLD_1			7
#define WEATHER_COLD_2			8
#define WEATHER_COLD_3			9
#define WEATHER_SEMI_ARID_S		10
#define WEATHER_ARID_S			11
#define WEATHER_VERY_ARID_S		12
#define WEATHER_TROPICAL_1		13
#define WEATHER_TROPICAL_2		14
#define WEATHER_TROPICAL_DRY	15
#define WEATHER_CAVE_SAND_1		16	//50% sand
#define WEATHER_CAVE_SAND_2		17	//100% sand
#define WEATHER_RAINY_1			18
#define WEATHER_RAINY_2			19
#define WEATHER_RAIN_ONLY_1		20
#define WEATHER_RAIN_ONLY_2		21
#define WEATHER_ALWAYS_SUN		22
#define WEATHER_ALWAYS_RAIN		23
#define WEATHER_ALWAYS_SAND		24
#define WEATHER_ALWAYS_HAIL		25


#endif
