ViridianGym_1F_MapScripts::
	.byte 0


VirGym_SorenBattle::
	lock
	msgbox VirGym_SorenBattle_Text_0
	msgbox VirGym_SorenBattle_Text_1
	release
	end


VirGym_SorenBattle_Text_0:
	.string "Ahaha! So you found me! How do you like\n"
	.string "my little den? I’m Soren, Kanto’s first\l"
	.string "and greatest expert on caves and\l"
	.string "tunnels! Three years ago, coal was\l"
	.string "found under Pewter City, and who would\l"
	.string "answer the call but me! That mine, ja,\l"
	.string "and all the riches that came with it...\l"
	.string "it’s all because of me!$"

VirGym_SorenBattle_Text_1:
	.string "Hah... but that is not what you’re here\n"
	.string "for, is it? No, you’re here for Soren the\l"
	.string "gym leader. Very well! My Pokémon are\l"
	.string "always willing to show why I’m also\l"
	.string "Kanto’s greatest Ground-type expert!\l"
	.string "Hahaha!$"
