ViridianPlainEFarmInside_MapScripts::
	.byte 0


ViridianPlainEFarmInside_Farmer::
	lock
	faceplayer
	msgbox ViridianPlainEFarmInside_Farmer_Text_0
	release
	end


ViridianPlainEFarmInside_Farmer_Text_0:
	.string "Why, hello!\n"
	.string "I'm the owner of this farm here.\l"
	.string "I don't have much to offer you yet. At\l"
	.string "least, not until my fence is fixed!\l"
	.string "Speaking of the fence, make sure you\l"
	.string "steer clear of my herd.\l"
	.string "They get quite the temper once they're\l"
	.string "out in the wild!$"
